### ISSUE TITLE
Add possibility to remove an invoice row

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#10]
There is a button `Add row` to add an invoice row, but there is no way to remove such rows.

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Not working. Steps to check:

1. Open new invoice page.
2. Create five rows.
3. Try to remove all the rows by right click on the first row and Remove row context menu item.

**Comment by krzysztofspilka** [comment]
@jakubklekota 

Works fine with two exceptions:

1. If paginated by 10 then can't remove the 11th, 21st, 31st etc. row using the context menu
2. Insert row > should work in place and be divided into "Insert row above" and "Insert row below" options, just like in our context menu demo http://docs.handsontable.com/0.20.2/demo-context-menu.html

**Comment by jakubklekota** [comment]
@krzysztofspilka 

> If paginated by 10 then can't remove the 11th, 21st, 31st etc. row using the context menu (that might be a problem in Handsontable)

Changed condition in context menu function which, improve delete row

> Insert row > should work in place and be divided into "Insert row above" and "Insert row below" options, just like in our context menu demo http://docs.handsontable.com/0.20.2/demo-context-menu.html

```Insert row above ``` and ```Insert row below ``` - we are waiting for the response of our idea activities related to rowIndex property

**Comment by miyconst** [comment]
> ... we are waiting for the response ...

Is it something we have to respond?

**Comment by krzysztofspilka** [comment]
@miyconst if we all agree that adding a rowIndex is the omly solution for now, then nope;)

**Comment by miyconst** [comment]
Well, I don't see any other/better solution. Rows should be sorted by some column, and the order of the rows should stay untouched after page reload.

If this takes much time, then leave it for now, adding a row is enough, other features are more important.

**Comment by krzysztofspilka** [comment]
Did some tests and

>If paginated by 10 then can't remove the 11th, 21st, 31st etc. row using the context menu (that might be a problem in Handsontable)

Works fine

>Insert row > should work in place and be divided into "Insert row above" and "Insert row below" options, just like in our context menu demo http://docs.handsontable.com/0.20.2/demo-context-menu.html

We need to add a rowIndex > todo. @jakubklekota please estimate it roughly so @miyconst don't have to worry we're about to spend too much time on it.

Also, a bug found:

- Create five rows
- Select all rows
- Open the context menu and try to insert a row

**Result:** this option is inactive
**Solution:** already fixed in Handsontable by Jan Siegel, we need to wait for the new release
**Notice:** actually nobody adds new rows like this ;)

**Comment by jakubklekota** [comment]
It's done - add ```RowIndex``` in database model, add function to calculate ```RowIndex``` property, add function to migrate data - update ```RowIndex``` when is ```0```

Work fine - tested by me :).

**Comment by miyconst** [comment]
Hm, what would happen when we support server side sorting? The RowIndex value will be messed up, and rows with index 1,6,3 might get selected for deleting, not, 1,2,3.

**Comment by jakubklekota** [comment]
@miyconst - I think this issues is to close, yes ?

**Comment by miyconst** [comment]
Yes. Looks good. Removing multiple rows also supported.
