### ISSUE TITLE
It should be possible to add rows to an existing invoice

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#13]
Right now it is only possible to add rows to new invoices:

![image](https://cloud.githubusercontent.com/assets/6435556/10629849/982773d2-77d2-11e5-82ef-2d026cdaf6b6.png)

But not possible when an invoice selected from the left panel to edit:

![image](https://cloud.githubusercontent.com/assets/6435556/10629859/ab5cf814-77d2-11e5-86b6-c1710650b438.png)

**Comment by jakubklekota** [comment]
fixed
