### ISSUE TITLE
Pagination logic should be on server side

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#16]
Starcounter application should be client side logic less.

The pagination methods `next` & `previous`:
https://github.com/handsoncode-apps/InvoiceDemo/blob/master/wwwroot/InvoiceDemo/InvoiceDetailsPage.html#L109

Should be moved to server side, and the `Page$` property should be reaonly. Right now it is possible to set `Page$ = -1`;

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Does not work properly:

![image](https://cloud.githubusercontent.com/assets/6435556/11661713/935a4d08-9dd3-11e5-81c3-f53ae565ba4f.png)

![image](https://cloud.githubusercontent.com/assets/6435556/11661746/aea2bc94-9dd3-11e5-8298-40ca61cab2cf.png)

Two pages look exactly the same.

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Looks to be fixed, but can't fully test because of: https://github.com/handsoncode-apps/InvoiceDemo/issues/11

**Comment by miyconst** [comment]
Pagination is working on server side, closing the issue in spite of switching pages causes lots of other side effects.
