### ISSUE TITLE
Add hot-table context menu with Delete & Insert actions

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#17]
The hot-table looks very like MS-Excel and many users got used to context menu items Delete row & Insert row.

**Comment by miyconst** [comment]
In the latest version context menu does not pop-up on right mouse click.

**Comment by krzysztofspilka** [comment]
Works well for me. Connected with #10 
@jakubklekota let @miyconst know when it's ready.

**Comment by miyconst** [comment]
This is how it looks for me:

![context-menu](https://cloud.githubusercontent.com/assets/6435556/11783763/27cc5946-a279-11e5-9803-0dff7656ad93.gif)

Chrome `Version 47.0.2526.80 m`

**Comment by jakubklekota** [comment]
@krzysztofspilka could you check it ? I improved load context menu.

**Comment by krzysztofspilka** [comment]
@jakubklekota will do that tomorrow

**Comment by krzysztofspilka** [comment]
@jakubklekota works fine for me. Tested, as always, on latest Chrome/FF.
@miyconst from now on a user won't be able to remove the last row, such action will only delete its content. This empty row won't be represented in a DB until you fill it with a content and then save.

**Comment by miyconst** [comment]
I am fine with it, as long as it is not saved in database.
