### ISSUE TITLE
Pressing remove row button automatically saves invoice without any validation

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#26]

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
What was the issue, and how it was fixed?

**Comment by jakubklekota** [comment]
Removed ```Transaction.Commit(); ``` in ```DeleteItem(int start, int end)``` method.
When ```Transaction.Commit(); ``` call, the new invoice object was stored in database.

**Comment by miyconst** [comment]
Okay. Closing the issue.
