### ISSUE TITLE
Somehow I ended up with two invoices with same ID

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#27]
![image](https://cloud.githubusercontent.com/assets/6435556/11662336/5996e1e6-9dd6-11e5-9026-647c9dccb05f.png)

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
What was the issue, and how it was fixed?

**Comment by jakubklekota** [comment]
Removed ```Transaction.Commit();``` in ```DeleteItem(int start, int end)``` method.
When ```Transaction.Commit();``` call, the new invoice object was stored in database, so we have the same ID, because default value for ```InvoiceNo``` is ```0```, and not auto increment via database, but manually add in code:

https://github.com/handsoncode-apps/InvoiceDemo/blob/master/InvoiceDetails.json.cs#L83

**Comment by miyconst** [comment]
Okay.

Consider adding a unique constrain to the table, so the issue won't appear in the future.
Not a requirements, low priority.
