### ISSUE TITLE
Console error on Invoice page

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#30]
```
http://localhost:8080/sys/puppet-redirect/src/puppet-redirect.html  404 (Not Found)
```

On http://localhost:8080/invoicedemo/invoices/1

**Comment by jakubklekota** [comment]
@miyconst which version of database you have ? Last nightly or last stable ? This error is on last nightly version - 2.1.865 of database, for last stable - 2.1.177 this error not present.

So can you tell me, it's error on my side ?

**Comment by miyconst** [comment]
Latest stable uses old version of `puppet-redirect`, the new one does not have `src` folder.
https://github.com/PuppetJs/puppet-redirect

**Comment by jakubklekota** [comment]
OK, thanks. Now i know

**Comment by jakubklekota** [comment]
ok - repair this bug. Change href

**Comment by miyconst** [comment]
Looks good.
