### ISSUE TITLE
Remove row button removes the last row, but should remove selected row

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#32]
Currently remove row button removes the last row.

If there is more than one page of rows, it is not visible, if something were made at all.
The last, not visible row got silently deleted, that is all.

The selected row should be removed instead of the last one.

**Comment by krzysztofspilka** [comment]
@miyconst aren't we duplicating the content menu options? Maybe we should go more lean and rely only on context menu (and the rest of configuration keep in a separate page)? For instance:

- Pagination limit > move to the config page
- Remove row button > delete
- Add row > delete and replace with "min-spare row" option + pre-defined text? (Like "start typing to add a new row")

Plus, to avoid paginating the invoices too often, increase the default number of invoices displayed per page to 20.

What do you think?

**Comment by miyconst** [comment]
@krzysztofspilka, those are good ideas for a production application, but this is a demo sample. That is why I would like to keep the features.

The [Remove] button is a duplicate of the context menu, and might not be presented in the real applications, but many systems still use this UI pattern, especially for tablets, where context menu is not that intuitive.

The [Page limit] default value could be moved to settings, and would be nice to see it there. But the select-box should be on the page as well.

The [Min spare row] value is very application specific, many systems would prefer to be able to remove all rows. So, you can move this value to settings.

I like the settings idea, but I would like to finish what we have now before adding some more features.

**Comment by krzysztofspilka** [comment]
@jakubklekota good thoughts of @miyconst, let's first make a fully functional demo and then add/remove new features if needed or requested by a certain end-user.

**Comment by jakubklekota** [comment]
@miyconst could you reproduce it ?

**Comment by miyconst** [comment]
Fixed.
