### ISSUE TITLE
Sorting should be on server side and should apply over all pages

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#34]

**Comment by jakubklekota** [comment]
@miyconst. I have problem with query to return items from starcounter.

This one - working fine:
```Db.SQL<InvoiceRow>("SELECT r FROM InvoiceRow r WHERE r.Invoice=? ORDER BY r.RowIndex ASC FETCH 10 OFFSET 0", invoice)```

but in this case:

``` Db.SQL<InvoiceRow>("SELECT r FROM InvoiceRow r WHERE r.Invoice=? ORDER BY ? ASC FETCH 10 OFFSET 0", invoice, "RowIndex") ```

I got error:
``` ScErrSqlInternalError (SCERR7000): Unexpected internal error in SQL module. Incorrect typeTerm: any
Version: 2.1.865.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7000.```

Do you know, why ?

**Comment by warpech** [comment]
@jakubklekota the [Variables](http://starcounter.io/guides/database/variables/) page says: 

> Note that you can only use ? to variables after the WHERE clause. You cannot, for instance, use ? to replace the class name of a query.

I am afraid the only way to do this is: 

```cs
var orderBy = "r.RowIndex";
var res = Db.SQL<InvoiceRow>("SELECT r FROM InvoiceRow r WHERE r.Invoice=? ORDER BY " + orderBy + " ASC FETCH ? OFFSET ?", invoice, 10, 0)
```

@k-rus can you confirm?

**Comment by k-rus** [comment]
I confirm that the variables can be used only for literals. Identifiers cannot be given through variables. Thus it is not possible to give variable to ORDER BY instead of the identifier.

**Comment by miyconst** [comment]
```cs
"ORDER BY " + orderBy;
```

Make sure to escape the value to avoid sql injections.

**Comment by jakubklekota** [comment]
@miyconst could you reproduce it ?

**Comment by miyconst** [comment]
The sorting work, but there are some blinking. It feels like every row of the table being replaced separately.

So, I can catch with my eye, how rows being replaced one by one.

It should be handsontable issue, so I close this one.
