### ISSUE TITLE
Right mouse button click reverts sorting in the table

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#37]
If I sort the table by any column and then press right mouse button, then the sorting gets restored automatically.

**Comment by krzysztofspilka** [comment]
I think that the mouse right-click should always invoke the context menu to keep the grid consistent with other grids/spreadsheets on the market. Also, I might want to conduct some operations on a sorted data - like remove/add the row using context menu. Are you sure we should implement this idea?

**Comment by miyconst** [comment]
@krzysztofspilka sorry, I don't get your question.

I simply want to see context menu for the item I click on, and nothing should happen with the grid itself.

**Comment by krzysztofspilka** [comment]
@miyconst sorry, at first I thought it is some kind of requirement;) but you're reporting a bug, alright. We can't reproduce it locally though. @jakubklekota any ideas how to check what's going on?

**Comment by jakubklekota** [comment]
@krzysztofspilka At this moment, do not

**Comment by miyconst** [comment]
@krzysztofspilka, @jakubklekota, yes, it looks like the bug was fixed together with performance issue. I will double check that and close the issue if so.

**Comment by jakubklekota** [comment]
@miyconst - what about this issues ? Is to close or not ?

**Comment by miyconst** [comment]
Confirm the fix.
